### PR TITLE
Windows CI

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
There is only one failure. Fails with `OUT_OF_HOST_MEMORY`

**Comment by inducer** [comment]
> There is only one failure. Fails with `OUT_OF_HOST_MEMORY`

You could skip or xfail that test on Windows.

**Comment by inducer** [comment]
Merged https://github.com/inducer/ci-support/pull/23. Could you re-point this at upstream ci-support?

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
Promptly failed on `main`: https://github.com/inducer/pyopencl/actions/runs/3192931480/jobs/5210961672#step:3:793

Could you take a look?

**Comment by isuruf** [comment]
That's a very weird error. I have no idea how the strides can ever be different.

```
_ test_slice[<context factory for <pyopencl.Device 'Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz' on 'Intel(R) OpenCL'>>] _
[gw0] win32 -- Python 3.10.6 D:\a\pyopencl\pyopencl\.miniforge3\envs\testing\python.exe
Traceback (most recent call last):
  File "D:\a\pyopencl\pyopencl\test\test_array.py", line 1150, in test_slice
    a_gpu[start:end] = tp(2)*b[start:end]
  File "D:\a\pyopencl\pyopencl\pyopencl\array.py", line 2291, in __setitem__
    self.setitem(subscript, value)
  File "D:\a\pyopencl\pyopencl\pyopencl\array.py", line 2266, in setitem
    raise NotImplementedError("cannot assign between arrays of "
NotImplementedError: cannot assign between arrays of differing strides
```

**Comment by inducer** [comment]
I agree it's weird, but I don't have time to deal with it now. Want me to revert while you investigate?

**Comment by inducer** [comment]
There might be something wrong with that test. Here's a crash on the Linux side:
https://github.com/inducer/pyopencl/actions/runs/3207693960/jobs/5242841641

**Comment by isuruf** [comment]
Ah I think I know the issue. There are some tests skipped in pyopencl because of zero sized arrays not supported in Intel CL.
We can have zero sized arrays in the test at https://github.com/inducer/pyopencl/blob/9e87128cc7907979eb9c3bbeaf765305a8e94004/test/test_array.py#L1141

**Pull request merged**
