### PR TITLE
Add support for initial in reductions

### PR DESCRIPTION
**Pull request by alexfikl**
* Added support for `initial` in `sum`, `min` and `max`.
* Added `any` and `all` as toplevel functions in `cl.array`.

### CODE REVIEW

**Comment by inducer** [comment]
Looks great, thanks!

cc @majosm

**Comment by inducer** [comment]
I suspect I should roll a release with this. Let me do that.

**Comment by inducer** [comment]
https://pypi.org/project/pyopencl/2021.2.11/

Should wind its way to conda forge soon.

**Comment by alexfikl** [comment]
> [pypi.org/project/pyopencl/2021.2.11](https://pypi.org/project/pyopencl/2021.2.11/)
> 
> Should wind its way to conda forge soon.

Thanks!

**Pull request merged**
