### PR TITLE
Add spinner for travis hanging

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by inducer** [comment]
Wow. So the other architectures are... just slow? :)

**Comment by isuruf** [comment]
Not sure. This is just a blind test. Can you enable pull request builds in travis-CI so that I can try it in this PR?

**Comment by inducer** [comment]
> Can you enable pull request builds in travis-CI so that I can try it in this PR?

Done.

**Comment by isuruf** [comment]
Travis build passed, but is shown as pending here.

**Comment by inducer** [comment]
Hmm... Travis seems super janky of late. Anyway, let's merge this and see what happens. Thanks for working on this!

**Comment by inducer** [comment]
Hmm. You've set it to draft... I'll take that as a sign that I maybe shouldn't jump the gun.

**Comment by isuruf** [comment]
Ah, marked it as ready now.

**Comment by isuruf** [comment]
Looks like master branch fails with timeouts, but PRs work. Weird.

**Pull request merged**
