### PR TITLE
ARRAY_KERNEL_EXEC_HOOK: estimate bytes/flops

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by inducer** [comment]
I don't think this belongs here. One important reason is that we don't really have a way of looking inside the kernel here, and therefore the `nops` generated is, at best, an estimate, and at worst, dead wrong.

Once #416 is in, the arrays themselves will appear as arguments to the kernel, which should make it possible to do this within the hook itself, which makes it more palatable to me.

Does that sound reasonable?

**Review by inducer — CHANGES_REQUESTED** [review]
I don't think this belongs here. One important reason is that we don't really have a way of looking inside the kernel here, and therefore the `nops` generated is, at best, an estimate, and at worst, dead wrong.

Once #416 is in, the arrays themselves will appear as arguments to the kernel, which should make it possible to do this within the hook itself, which makes it more palatable to me.

Does that sound reasonable?

**Comment by matthiasdiener** [comment]
> I don't think this belongs here. One important reason is that we don't really have a way of looking inside the kernel here, and therefore the `nops` generated is, at best, an estimate, and at worst, dead wrong.
> 
> Once #416 is in, the arrays themselves will appear as arguments to the kernel, which should make it possible to do this within the hook itself, which makes it more palatable to me.
> 
> Does that sound reasonable?

Sure, that sounds fine!

**Comment by matthiasdiener** [comment]
Abandoned in favor of implementing this directly in mirgecom: github.com/illinois-ceesd/mirgecom/pull/193

**Pull request closed without merging**
