### PR TITLE
Fix not finding pocl when /etc/OpenCL/vendors doesn't exist

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by inducer** [comment]
Could you put this on Gitlab for CI?

**Comment by isuruf** [comment]
@inducer, is there docker access in Gitlab?

**Comment by inducer** [comment]
Yes. Just make sure you have a Docker tag on that job.

**Comment by inducer** [comment]
Oh--just saw that this only touches the Travis stuff that runs here. Nvm.

**Pull request merged**
