### PR TITLE
Fix a build failure (kernel cloning introduced in 2.1, not 2.0)

### PR DESCRIPTION
**Pull request by pjaaskel**

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! (It uses the correct `#ifdef` in the header, I checked.)

**Comment by pjaaskel** [comment]
@inducer FYI: https://github.com/pocl/pocl/commit/9fefe97b01ff1aa02ef046932cd5ff49a4510341, there was also another issue with the latest master revision I encountered when testing for soon-to-be-branched pocl 1.6. This was related to some AMD extension, and I couldn't debug it further due to lack of time. If you want to check, it can be reproduced by setting that GIT_TAG to the latest master revision (or removing it) and then 'make prepare_examples && ctest -L PyOpenCL'. Otherwise, we'll just keep the known-working-latest-revision in this test suite and update it whenever we find the time.

**Comment by inducer** [comment]
Thanks for the heads-up. I tried to take a look, but:
```
cmake -D LLVM_CONFIG=/usr/bin/llvm-config-10 -DENABLE_TESTSUITES=PyOpenCL -DEXAMPLES_USE_GIT_MASTER=ON .. && make -j15 && make prepare_examples
Scanning dependencies of target prepare_examples
Built target prepare_examples
$ ctest -L PyOpenCL
Test project /home/andreas/pack/pocl/build
No tests were found!!!
```
and
```
cmake -D LLVM_CONFIG=/usr/bin/llvm-config-10 -DENABLE_TESTSUITES=all -DEXAMPLES_USE_GIT_MASTER=ON .. && make -j15 && make prepare_examples
```
dies somewhere while building Glow:
```
-- Performing Test HAVE_POSIX_REGEX                                                                                                                                                                                                             
-- Performing Test HAVE_POSIX_REGEX                                                                                                                                                                                                             
-- Performing Test HAVE_POSIX_REGEX -- success                                                                                                                                                                                                  
-- Performing Test HAVE_STEADY_CLOCK                                                                                                                                                                                                            
-- Performing Test HAVE_STEADY_CLOCK                                                                                                                                                                                                            
-- Performing Test HAVE_STEADY_CLOCK -- success                                                                                                                                                                                                 
-- Found PythonInterp: /bin/python3.9 (found version "3.9")                                                                                                                                                                                     
CMake Error at tests/unittests/CMakeLists.txt:603 (message):                                                                                                                                                                                    
  unable to find clang, cannot build the CPU runtime  
```
Any tips?

**Comment by pjaaskel** [comment]
Hard to say from these log pastes. Do you see PyOpenCL listed in the enabled test suites in the cmake step?

**Comment by inducer** [comment]
Do you have a log paste of the PyOpenCL issue you saw?

**Comment by pjaaskel** [comment]
Unfortunately I didn't capture it and I'm unable (due to other tasks) to get back to this soon :I

**Pull request merged**
