### PR TITLE
Compiler cache: honor XDG_CACHE_HOME on MacOS

### PR DESCRIPTION
**Pull request by matthiasdiener**
Similar to https://github.com/inducer/pytools/pull/204

### CODE REVIEW

**Comment by alexfikl** [comment]
I understand the need here, but I'm a curious about some things:
* Why only on macOS and not Windows? Can the Windows paths be overwritten by environment variables?
* If we're forcing a non-native environment variable on other OSes, why not use something like `PYOPENCL_CACHE_DIR` (to mirror `PYOPENCL_NO_CACHE`)?

**Comment by matthiasdiener** [comment]
> * Why only on macOS and not Windows? Can the Windows paths be overwritten by environment variables?

Looking at https://github.com/platformdirs/platformdirs/blob/main/src/platformdirs/windows.py#L251, I guess so, but my knowledge of Windows is almost zero 😞 

> * If we're forcing a non-native environment variable on other OSes, why not use something like `PYOPENCL_CACHE_DIR` (to mirror `PYOPENCL_NO_CACHE`)?

We could add `PYOPENCL_CACHE_DIR`, but the current goal was to make the disk caching selection consistent across loopy and pyopencl, for both Mac and Linux. 

Edit: another important reason: _Pocl_ also honors `XDG_CACHE_HOME` on MacOS.

**Comment by alexfikl** [comment]
> Edit: another important reason: _Pocl_ also honors `XDG_CACHE_HOME` on MacOS.

Fair enough, but they just fallback to it and also have a [`POCL_CACHE_DIR`](http://portablecl.org/docs/html/env_variables.html) (at least that's what the docs say).

**Comment by matthiasdiener** [comment]
This is ready for review @inducer.

**Comment by inducer** [comment]
LGTM, thanks!

**Pull request merged**
