### PR TITLE
Multi __setitem__ numpy compliance

### LINKED ISSUE #72: Make __setitem__ to fill all subscript positions even if size of values array is less than subscript size.
It's needed to be more compatible with numpy. For example:

```
>>> sx = array.empty(queue, 4, np.int32)
>>> sx
array([0, 0, 0, 0], dtype=int32)
>>> idx = clrandom.rand(queue, 2, np.int32, luxury=None, a=0, b=4)
>>> idx
array([3, 1], dtype=int32)
>>> val = clrandom.rand(queue, 1, np.int32, luxury=None, a=0, b=99)
>>> val
array([48], dtype=int32)
>>> sx[idx] = val
>>> sx
array([ 0,  0,  0, 48], dtype=int32) #Only one position filled

>>> npsx = np.zeros(sx.shape, dtype=sx.dtype)
>>> npsx
array([0, 0, 0, 0], dtype=int32)
>>> npval = np.array([48], dtype=np.int32)
>>> npval
array([48], dtype=int32)
>>> npidx = np.array([3, 1], dtype=np.int32)
>>> npidx
array([3, 1], dtype=int32)
>>> npsx[npidx] = npval
>>> npsx
array([ 0, 48,  0, 48], dtype=int32) #Both positions filled
```

Also, as I observed in other cases, numpy is using equation like `values[n%values.size]` (where n is current subscription position) to get value for current subscription index. For example:

```
>>> npval = np.array([48, 32], dtype=np.int32)
>>> npidx = np.array([1, 2, 3], dtype=np.int32)
>>> npsx = np.zeros((4,), dtype=np.int32)
>>> npsx
array([0, 0, 0, 0], dtype=int32)
>>> npsx[npidx] = npval
>>> npsx
array([ 0, 48, 32, 48], dtype=int32)

>>> npidx = np.array([2, 3, 1], dtype=np.int32)
>>> npsx = np.zeros((4,), dtype=np.int32)
>>> npsx[npidx] = npval
>>> npsx
array([ 0, 48, 48, 32], dtype=int32)
```

I think, it is possible to make custom kernels for cases like:
- values is array with size 1
- values is array with size less than subscription size
- values is array with size bigger or equal than subscription size

### PR DESCRIPTION
**Pull request by hrfuller**
Fixes #72 
--------------------------------------------------------
* Pass new args to the `get_put_kernel` which direct whether to fill i*th* array with a single value or use modulo mode.

* Add unit tests for numpy compliance and filling multiple CL arrays at once using the `mutli_put` method.

### CODE REVIEW

**Comment by inducer** [comment]
Looks good. CI running:

https://gitlab.tiker.net/inducer/pyopencl/merge_requests/3

**Comment by inducer** [comment]
Some failures:

https://gitlab.tiker.net/inducer/pyopencl/pipelines/3454

* Flake8 doesn't pass
* Numpypy doesn't match the behavior, maybe file a bug with them, and xfail the test on Pypy

**Comment by hrfuller** [comment]
Okay. Fixed the Flake8 indent issue and XFAILed the tests for numpypy.

**Comment by inducer** [comment]
Pushed commits over:
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/3

**Comment by inducer** [comment]
Passed. Thanks for your contribution!

**Pull request merged**
