### PR TITLE
remove print-binary.py

### PR DESCRIPTION
**Pull request by matthiasdiener**
With `decode()` and pocl, this results in the following error:

```console
$ python experiments/print-binary.py foo.cl
Traceback (most recent call last):
  File "/Users/mdiener/Work/drivers_y3-prediction-esdg/emirge/pyopencl/experiments/print-binary.py", line 13, in <module>
    print(prg.binaries[0].decode("utf-8"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 8: invalid start byte
```

With this PR:

```console
$ python experiments/print-binary.py foo.cl
poclbin|Ç¿zÖ	LN/PIKEMMJELAABPLIMDDGLDMIKPKNLCOPMBLENO
                                                          /program.bcpÞÀ
[...]
```

This is the only file in `experiments`, so I thought it may be a candidate to move to `scripts`.

### CODE REVIEW

**Comment by isuruf** [comment]
`contrib/cldis.py` has kind of the same functionality right?

**Comment by inducer** [comment]
Yeah, let's just get rid of `print-binary`.

**Comment by matthiasdiener** [comment]
Sounds good, I changed this PR to remove it.

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
