### PR TITLE
move directory creation inside the wheel context

### LINKED ISSUE #438: Wheel creation creates .libs file which breaks installation of binary wheels
Related to https://github.com/isuruf/ocl-wheels/issues/3 (and causing similar errors with `pocl`)

The OCL Dev License file is copied to another file [here](https://github.com/inducer/pyopencl/blob/main/scripts/fix-wheel.py#L14), named `.libs`; this should be replaced with a directory. Happy to PR cc: @vincentsarago

### PR DESCRIPTION
**Pull request by drewbo**
actually close #438 cc: @isuruf thanks for the tip and apologize for the double PR

### CODE REVIEW

**Comment by inducer** [comment]
Could you enable maintainer pushes? Alternatively, merge this up to main.

**Comment by inducer** [comment]
Thanks!

**Comment by inducer** [comment]
2021.1.4 released, hot off the presses just for you. Wheel builds should show up soon. Let me know if you continue to have trouble.

**Comment by drewbo** [comment]
Thanks! The package installs correctly now but runs into the same error seen here: https://github.com/inducer/pyopencl/issues/391#issuecomment-717515393, I'll continue to investigate and open another issue/PR if necessary

**Pull request merged**
