### PR TITLE
Make sure there are no 0-sized arrays in test_slice

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by inducer** [comment]
What exactly is causing issues for the Intel ICD here? Empty NDRanges? Zero-size allocations? Both of these are already handled specially...

**Comment by isuruf** [comment]
Multiplying a zero sized array by a scalar.

**Comment by inducer** [comment]
Yeah... but *what specifically* about that is causing issues? Any idea?

**Comment by isuruf** [comment]
Looks like this error happens in apple implementation too as pointed out by @alexfikl in https://github.com/inducer/pyopencl/pull/616#issuecomment-1279691695

**Comment by alexfikl** [comment]
> Looks like this error happens in apple implementation too as pointed out by @alexfikl in [#616 (comment)](https://github.com/inducer/pyopencl/pull/616#issuecomment-1279691695)

Hasn't happened in the last 3 runs though, so not quite sure what to make of that. Is it intermittent on Intel as well?

**Comment by isuruf** [comment]
Yes, you need `end = randrange(start, ary_len) == start` for the error to occur.

**Comment by alexfikl** [comment]
> Yes, you need `end = randrange(start, ary_len) == start` for the error to occur.

Ah, thanks! Missed the random in that test.

**Comment by inducer** [comment]
Thanks! Superseded by https://github.com/inducer/pyopencl/pull/638.

**Pull request closed without merging**
