### PR TITLE
Fix `nan` handling in `min`/`max`/`minimum`/`maximum`

### LINKED ISSUE #583: Reductions on arrays containing `nan` give unexpected results
**Describe the bug**
Array reductions such as `min` and `max` produce unexpected results when `nan`s are present in the input array.

**To Reproduce**
```python
import pyopencl as cl
import pyopencl.array as cla
import numpy as np

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

a = np.full(10, np.nan)
a_dev = cla.to_device(queue, a)

print(f"{cla.max(a_dev)=}")

b = np.full(10, np.nan)
b[0] = 1.
b_dev = cla.to_device(queue, b)

print(f"{cla.max(b_dev)=}")
```
Output:

```
cla.max(a_dev)=cl.Array(-inf)
cla.max(b_dev)=cl.Array(1.)
```

**Expected behavior**
Ideally these should both return `cl.Array(nan)`?

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - ICD Loader and version: whatever macOS uses (khronos-opencl-icd-loader?)
 - ICD and version: pocl 1.8
 - CPU/GPU: Intel i7
  - Python version: 3.9
  - PyOpenCL version: 2022.1.6

### PR DESCRIPTION
**Pull request by majosm**
Closes #583.

To-do:

- [x] Add failing tests
- [x] Fix the issue

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for putting this together! This is a bit hokey, but it ought to do the trick. Take a look, and if this looks good to you, then we can go ahead and merge this.

**Comment by inducer** [comment]
OK, next attempt. :)

**Review by majosm — COMMENTED** [review]
Looks good to me. 🙂

**Comment by inducer** [comment]
Thanks! In it goes.

**Pull request merged**
