### PR TITLE
Add types and clean up docs in reduction.py

### PR DESCRIPTION
**Pull request by alexfikl**
Similar to #642.

### CODE REVIEW

**Comment by alexfikl** [comment]
Hm, not quite sure what's going on with that `pylint` failure. Any idea?

EDIT: Seems to be failing on `main` as well:
https://github.com/inducer/pyopencl/actions/runs/3354052903

**Comment by inducer** [comment]
Possibly https://github.com/inducer/ci-support/commit/547f43a21b8151c920462766e6b5edcb30da2501 will help?

**Comment by alexfikl** [comment]
> Possibly [inducer/ci-support@547f43a](https://github.com/inducer/ci-support/commit/547f43a21b8151c920462766e6b5edcb30da2501) will help?

Thanks! I'm running 2.15 locally and it's not showing any of those weird errors.

**Review by inducer — APPROVED** [review]
Thanks! This'll go after #649.

**Pull request merged**
