### PR TITLE
Fix strides for 0-sized c-contiguous arrays

### PR DESCRIPTION
**Pull request by alexfikl**
Companion to inducer/compyte#36.

### CODE REVIEW

**Comment by alexfikl** [comment]
@inducer Updated `compyte` in here (hopefuly in the proper way?).

**Comment by inducer** [comment]
I guess that's looking like the second pyopencl release of the day once this is merged. :)

**Comment by inducer** [comment]
Also, LGTM! And thanks!

**Comment by alexfikl** [comment]
> I guess that's looking like the second pyopencl release of the day once this is merged. :)

:tada:

**Comment by inducer** [comment]
https://pypi.org/project/pyopencl/2021.2.8/#history

**Pull request merged**
