### PR TITLE
Make maximum and minimum work with scalars

### PR DESCRIPTION
**Pull request by alexfikl**
Required to make inducer/arraycontext#103 work in all cases.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks!

**Comment by alexfikl** [comment]
> Thanks!

Hopefully this wasn't too fast :worried:. I tested it locally and it seemed to pass all the tests that were failing in inducer/meshmode#273, but didn't get to run the whole CI properly.

**Comment by inducer** [comment]
https://pypi.org/project/pyopencl/2021.2.9/

**Comment by inducer** [comment]
I looked it over, it seemed fine... do you have any specific potential breakage in mind?

**Comment by alexfikl** [comment]
> I looked it over, it seemed fine... do you have any specific potential breakage in mind?

Not really, the tests should cover it pretty well.

Thanks for releasing it so quickly too!

**Comment by inducer** [comment]
The CI said it was good enough. If it turns out broken, we'll just fix it. :) (And improve the CI so it doesn't happen again.)

**Pull request merged**
